### ISSUE TITLE
Error while making on kernel 6.16.8 on Arch

### ISSUE THREAD

**Issue by ATUK-OoD** [pelrun/hp-omen-linux-module#35]
Hello to everyone. There are more issues as it seems, because there is an error while building on kernel 6.16.8.

some hopefully relevant specifications:

OS: Arch Linux x86_64 
Host: HP OMEN Laptop 15-en1001np Renew
Kernel: 6.16.8-arch3-1 

`sudo make install`
returns
```
dkms install .
Deprecated feature: CLEAN (/usr/src/hp-omen-wmi-0.9/dkms.conf)
Creating symlink /var/lib/dkms/hp-omen-wmi/0.9/source -> /usr/src/hp-omen-wmi-0.9

Sign command: /usr/lib/modules/6.16.8-arch3-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j16 KERNELRELEASE=6.16.8-arch3-1 -C src/ KERNELDIR=/lib/modules/6.16.8-arch3-1/build

Error! Bad return status for module build on kernel: 6.16.8-arch3-1 (x86_64)
Consult /var/lib/dkms/hp-omen-wmi/0.9/build/make.log for more information.
make: *** [Makefile:2: install] Error 10
```

and cat /var/lib/dkms/hp-omen-wmi/0.9/build/make.log 
returns
```
DKMS (dkms-3.2.2) make.log for hp-omen-wmi/0.9 for kernel 6.16.8-arch3-1 (x86_64)
Thu Oct  9 07:31:49 PM CEST 2025

Building module(s)
# command: make -j16 KERNELRELEASE=6.16.8-arch3-1 -C src/ KERNELDIR=/lib/modules/6.16.8-arch3-1/build
make[1]: Entering directory '/var/lib/dkms/hp-omen-wmi/0.9/build/src'
make -C /lib/modules/6.16.8-arch3-1/build M=$PWD
make[2]: Entering directory '/usr/lib/modules/6.16.8-arch3-1/build'
make[3]: Entering directory '/var/lib/dkms/hp-omen-wmi/0.9/build/src'
  CC [M]  hp-wmi.o
hp-wmi.c: In function ‘hp_wmi_notify’:
hp-wmi.c:556:12: error: implicit declaration of function ‘wmi_get_event_data’; did you mean ‘acpi_get_event_status’? [-Wimplicit-function-declaration]
  556 |   status = wmi_get_event_data(value, &response);
      |            ^~~~~~~~~~~~~~~~~~
      |            acpi_get_event_status
hp-wmi.c: In function ‘hp_wmi_input_setup’:
hp-wmi.c:709:57: error: passing argument 2 of ‘wmi_install_notify_handler’ from incompatible pointer type [-Wincompatible-pointer-types]
  709 |   status = wmi_install_notify_handler(HPWMI_EVENT_GUID, hp_wmi_notify, NULL);
      |                                                         ^~~~~~~~~~~~~
      |                                                         |
      |                                                         void (*)(u32,  void *) {aka void (*)(unsigned int,  void *)}
In file included from hp-wmi.c:27:
/usr/lib/modules/6.16.8-arch3-1/build/include/linux/acpi.h:406:60: note: expected ‘wmi_notify_handler’ {aka ‘void (*)(union acpi_object *, void *)’} but argument is of type ‘void (*)(u32,  void *)’ {aka ‘void (*)(unsigned int,  void *)’}
  406 |                                         wmi_notify_handler handler, void *data);
      |                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~
hp-wmi.c:547:13: note: ‘hp_wmi_notify’ declared here
  547 | static void hp_wmi_notify(u32 value, void *context)
      |             ^~~~~~~~~~~~~
/usr/lib/modules/6.16.8-arch3-1/build/include/linux/acpi.h:393:16: note: ‘wmi_notify_handler’ declared here
  393 | typedef void (*wmi_notify_handler) (union acpi_object *data, void *context);
      |                ^~~~~~~~~~~~~~~~~~
In file included from /usr/lib/modules/6.16.8-arch3-1/build/include/linux/printk.h:6,
                 from /usr/lib/modules/6.16.8-arch3-1/build/include/asm-generic/bug.h:22,
                 from /usr/lib/modules/6.16.8-arch3-1/build/arch/x86/include/asm/bug.h:103,
                 from /usr/lib/modules/6.16.8-arch3-1/build/arch/x86/include/asm/alternative.h:9,
                 from /usr/lib/modules/6.16.8-arch3-1/build/arch/x86/include/asm/barrier.h:5,
                 from /usr/lib/modules/6.16.8-arch3-1/build/include/asm-generic/bitops/generic-non-atomic.h:7,
                 from /usr/lib/modules/6.16.8-arch3-1/build/include/linux/bitops.h:28,
                 from /usr/lib/modules/6.16.8-arch3-1/build/include/linux/kernel.h:23,
                 from hp-wmi.c:19:
hp-wmi.c: At top level:
hp-wmi.c:1249:22: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Wincompatible-pointer-types]
 1249 |   .remove = __exit_p(hp_wmi_bios_remove),
      |                      ^~~~~~~~~~~~~~~~~~
/usr/lib/modules/6.16.8-arch3-1/build/include/linux/init.h:395:21: note: in definition of macro ‘__exit_p’
  395 | #define __exit_p(x) x
      |                     ^
hp-wmi.c:1249:22: note: (near initialization for ‘hp_wmi_driver.remove’)
 1249 |   .remove = __exit_p(hp_wmi_bios_remove),
      |                      ^~~~~~~~~~~~~~~~~~
/usr/lib/modules/6.16.8-arch3-1/build/include/linux/init.h:395:21: note: in definition of macro ‘__exit_p’
  395 | #define __exit_p(x) x
      |                     ^
hp-wmi.c:1176:19: note: ‘hp_wmi_bios_remove’ declared here
 1176 | static int __exit hp_wmi_bios_remove(struct platform_device *device)
      |                   ^~~~~~~~~~~~~~~~~~
make[5]: *** [/usr/lib/modules/6.16.8-arch3-1/build/scripts/Makefile.build:287: hp-wmi.o] Error 1
make[4]: *** [/usr/lib/modules/6.16.8-arch3-1/build/Makefile:2003: .] Error 2
make[3]: *** [/usr/lib/modules/6.16.8-arch3-1/build/Makefile:248: __sub-make] Error 2
make[3]: Leaving directory '/var/lib/dkms/hp-omen-wmi/0.9/build/src'
make[2]: *** [Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/usr/lib/modules/6.16.8-arch3-1/build'
make[1]: *** [Makefile:5: default] Error 2
make[1]: Leaving directory '/var/lib/dkms/hp-omen-wmi/0.9/build/src'

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------
```

I've tried playing with the code, but nothing really works, mainly because I have no idea what I'm really doing...
Any suggestions or fixes will be really welcomed.
Thanks to everyone for any help.

**Comment by imroux** [comment]
You need this module to get patched for every new linux kernel version accordingly. There's a fork https://github.com/ranisalt/hp-omen-linux-module
I just tested its rebase-6.15 branch on current arch 6.17.6-arch1-1 kernel and it works fine.

**Comment by dedius** [comment]
> You need this module to get patched for every new linux kernel version accordingly. There's a fork https://github.com/ranisalt/hp-omen-linux-module I just tested its rebase-6.15 branch on current arch 6.17.6-arch1-1 kernel and it works fine.

It works also with kernel  6.17.0-8-generic in Ubuntu
